### ISSUE TITLE
CloudBees builds fail due to unaccapted licenses

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab.android#448]
I have made some experience with Gitlab CI and had the same issue. In Gitlab CI I can define a set of commands which will be executed. When you (@digitaldan) can also do this in CloudBees, I can post the command to accept all licenses here.

**Comment by mueller-ma** [comment]
Other error related to cloudbees. @kaikreuzer 
![jenkins](https://user-images.githubusercontent.com/22525368/32516632-43da34f6-c404-11e7-9f6c-a208677f6443.JPG)

**Comment by mueller-ma** [comment]
In Gitlab you can specify a file which will be executed by each commit.
```
image: jangrewe/gitlab-ci-android

stages:
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  stage: build
  script:
  - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/apk/app-debug.apk
```
Taken from https://github.com/jangrewe/gitlab-ci-android

The first line specifies the docker image which will be used as build enviroment, we just have to look at their dockerfile (file which is used to built the docker container) and see how they accept the licenses:
```
mkdir -p $ANDROID_HOME/licenses/ \
  && echo "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/android-sdk-license \
&& echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
```

@digitaldan Can you try to add this line to the "jenkins file" if such exists?
